export const MOCK_TECH_STACK_QUERY = {
  sanityHomepage: {
    _rawTechStack: [
      {
        _key: '54cbc02c79c8',
        _type: 'block',
        children: [
          {
            _key: 'a8538e1e992d0',
            _type: 'span',
            marks: [],
            text: 'As a graduate of a web development bootcamp, I have a strong foundation in modern ',
          },
          {
            _key: 'a8538e1e992d1',
            _type: 'span',
            marks: ['ac3c09a79322'],
            text: 'HTML',
          },
          {
            _key: 'a8538e1e992d2',
            _type: 'span',
            marks: [],
            text: ' and ',
          },
          {
            _key: 'a8538e1e992d3',
            _type: 'span',
            marks: ['499d5b0f2084'],
            text: 'CSS',
          },
          {
            _key: 'a8538e1e992d4',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: 'ac3c09a79322',
            _type: 'link',
            href: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
          },
          {
            _key: '499d5b0f2084',
            _type: 'link',
            href: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
          },
        ],
        style: 'normal',
      },
      {
        _key: '59f5cab64cb3',
        _type: 'block',
        children: [
          {
            _key: '59c54a60149b0',
            _type: 'span',
            marks: [],
            text: 'I follow industry newsletters to stay at the forefront of modern ',
          },
          {
            _key: '59c54a60149b1',
            _type: 'span',
            marks: ['ab77b8063c5a'],
            text: 'JavaScript',
          },
          {
            _key: '59c54a60149b2',
            _type: 'span',
            marks: [],
            text: ', and I make my code type-safe with ',
          },
          {
            _key: '59c54a60149b3',
            _type: 'span',
            marks: ['7663a645f359'],
            text: 'TypeScript',
          },
          {
            _key: '59c54a60149b4',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: 'ab77b8063c5a',
            _type: 'link',
            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
          },
          {
            _key: '7663a645f359',
            _type: 'link',
            href: 'https://www.typescriptlang.org/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '22c2fabd7ef2',
        _type: 'block',
        children: [
          {
            _key: 'cf9de6fcedf30',
            _type: 'span',
            marks: [],
            text: "When it comes to JavaScript libraries, I'm very much a ",
          },
          {
            _key: 'cf9de6fcedf31',
            _type: 'span',
            marks: ['2bbdbd14d751'],
            text: 'React',
          },
          {
            _key: 'cf9de6fcedf32',
            _type: 'span',
            marks: [],
            text: ' developer.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '2bbdbd14d751',
            _type: 'link',
            href: 'https://react.dev/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '743854ee1090',
        _type: 'block',
        children: [
          {
            _key: '75db675b3bc80',
            _type: 'span',
            marks: [],
            text: "React frameworks I've worked with include ",
          },
          {
            _key: '75db675b3bc81',
            _type: 'span',
            marks: ['21ab7e3b74a5'],
            text: 'Gatsby',
          },
          {
            _key: '75db675b3bc82',
            _type: 'span',
            marks: [],
            text: ' and ',
          },
          {
            _key: '75db675b3bc83',
            _type: 'span',
            marks: ['454000fb9339'],
            text: 'Next.js',
          },
          {
            _key: '75db675b3bc84',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 2,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '21ab7e3b74a5',
            _type: 'link',
            href: 'https://www.gatsbyjs.com/',
          },
          {
            _key: '454000fb9339',
            _type: 'link',
            href: 'https://nextjs.org/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '74ea312e0281',
        _type: 'block',
        children: [
          {
            _key: 'b3a4a7cc24010',
            _type: 'span',
            marks: [],
            text: 'I manage React state with APIs like ',
          },
          {
            _key: 'b3a4a7cc24011',
            _type: 'span',
            marks: ['8995ad71ad23'],
            text: 'React Context',
          },
          {
            _key: 'b3a4a7cc24012',
            _type: 'span',
            marks: [],
            text: ' and libraries like ',
          },
          {
            _key: 'b3a4a7cc24013',
            _type: 'span',
            marks: ['0b994c3fb1cd'],
            text: 'Apollo Client',
          },
          {
            _key: 'b3a4a7cc24014',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: 'b3a4a7cc24015',
            _type: 'span',
            marks: ['6782d63b0ee8'],
            text: 'Recoil.js',
          },
          {
            _key: 'b3a4a7cc24016',
            _type: 'span',
            marks: [],
            text: ', and ',
          },
          {
            _key: 'b3a4a7cc24017',
            _type: 'span',
            marks: ['cfba1579c7c1'],
            text: 'Redux',
          },
          {
            _key: 'b3a4a7cc24018',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 2,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '8995ad71ad23',
            _type: 'link',
            href: 'https://react.dev/learn/passing-data-deeply-with-context',
          },
          {
            _key: '0b994c3fb1cd',
            _type: 'link',
            href: 'https://www.apollographql.com/docs/react/',
          },
          {
            _key: '6782d63b0ee8',
            _type: 'link',
            href: 'https://recoiljs.org/',
          },
          {
            _key: 'cfba1579c7c1',
            _type: 'link',
            href: 'https://redux.js.org/',
          },
        ],
        style: 'normal',
      },
      {
        _key: 'f93171b6d96a',
        _type: 'block',
        children: [
          {
            _key: 'babc861ea6170',
            _type: 'span',
            marks: [],
            text: 'I enjoy building user interfaces with CSS frameworks like ',
          },
          {
            _key: 'babc861ea6171',
            _type: 'span',
            marks: ['263677bd118a'],
            text: 'Tailwind CSS',
          },
          {
            _key: 'babc861ea6172',
            _type: 'span',
            marks: [],
            text: ' and component libraries like ',
          },
          {
            _key: 'babc861ea6173',
            _type: 'span',
            marks: ['824ccc74126e'],
            text: 'MUI',
          },
          {
            _key: 'babc861ea6174',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '263677bd118a',
            _type: 'link',
            href: 'https://tailwindcss.com/',
          },
          {
            _key: '824ccc74126e',
            _type: 'link',
            href: 'https://mui.com/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '5291f4650c3f',
        _type: 'block',
        children: [
          {
            _key: '74ea2ee011ee0',
            _type: 'span',
            marks: [],
            text: "I'm comfortable working with data from both ",
          },
          {
            _key: '74ea2ee011ee1',
            _type: 'span',
            marks: ['03cc004a3544'],
            text: 'REST',
          },
          {
            _key: '74ea2ee011ee2',
            _type: 'span',
            marks: [],
            text: ' and ',
          },
          {
            _key: '74ea2ee011ee3',
            _type: 'span',
            marks: ['8755a20596ee'],
            text: 'GraphQL',
          },
          {
            _key: '74ea2ee011ee4',
            _type: 'span',
            marks: [],
            text: ' APIs.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '03cc004a3544',
            _type: 'link',
            href: 'https://en.wikipedia.org/wiki/REST',
          },
          {
            _key: '8755a20596ee',
            _type: 'link',
            href: 'https://graphql.org/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '0f845b65b9f4',
        _type: 'block',
        children: [
          {
            _key: '0c5464e7ca0c0',
            _type: 'span',
            marks: [],
            text: "While I specialize in front-end development, I've built full-stack applications using technologies like ",
          },
          {
            _key: '0c5464e7ca0c1',
            _type: 'span',
            marks: ['acab94ac652e'],
            text: 'Node.js',
          },
          {
            _key: '0c5464e7ca0c2',
            _type: 'span',
            marks: [],
            text: ' , ',
          },
          {
            _key: '0c5464e7ca0c3',
            _type: 'span',
            marks: ['5fcfafa9b95e'],
            text: 'Express',
          },
          {
            _key: '0c5464e7ca0c4',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: '0c5464e7ca0c5',
            _type: 'span',
            marks: ['f16356c578ad'],
            text: 'Apollo Server',
          },
          {
            _key: '0c5464e7ca0c6',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: '0c5464e7ca0c7',
            _type: 'span',
            marks: ['581a4c55172f'],
            text: 'MongoDB',
          },
          {
            _key: '0c5464e7ca0c8',
            _type: 'span',
            marks: [],
            text: ', and ',
          },
          {
            _key: '0c5464e7ca0c9',
            _type: 'span',
            marks: ['29c354fe977b'],
            text: 'Firebase',
          },
          {
            _key: '0c5464e7ca0c10',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: 'acab94ac652e',
            _type: 'link',
            href: 'https://nodejs.org/en',
          },
          {
            _key: '5fcfafa9b95e',
            _type: 'link',
            href: 'https://expressjs.com/',
          },
          {
            _key: 'f16356c578ad',
            _type: 'link',
            href: 'https://www.apollographql.com/docs/apollo-server/',
          },
          {
            _key: '581a4c55172f',
            _type: 'link',
            href: 'https://www.mongodb.com/',
          },
          {
            _key: '29c354fe977b',
            _type: 'link',
            href: 'https://firebase.google.com/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '1b60cd7989c2',
        _type: 'block',
        children: [
          {
            _key: 'b47516fe0ef30',
            _type: 'span',
            marks: [],
            text: 'I have experience organizing and managing web content using ',
          },
          {
            _key: 'b47516fe0ef31',
            _type: 'span',
            marks: ['0992596daf77'],
            text: 'Sanity',
          },
          {
            _key: 'b47516fe0ef32',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: 'b47516fe0ef33',
            _type: 'span',
            marks: ['2d17c5fe9756'],
            text: 'Strapi',
          },
          {
            _key: 'b47516fe0ef34',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: 'b47516fe0ef35',
            _type: 'span',
            marks: ['f5626f953b17'],
            text: 'Shopify',
          },
          {
            _key: 'b47516fe0ef36',
            _type: 'span',
            marks: [],
            text: ', and ',
          },
          {
            _key: 'b47516fe0ef37',
            _type: 'span',
            marks: ['f50acaeec38c'],
            text: 'WordPress',
          },
          {
            _key: 'b47516fe0ef38',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '0992596daf77',
            _type: 'link',
            href: 'https://www.sanity.io/',
          },
          {
            _key: '2d17c5fe9756',
            _type: 'link',
            href: 'https://strapi.io/',
          },
          {
            _key: 'f5626f953b17',
            _type: 'link',
            href: 'https://www.shopify.com/ca',
          },
          {
            _key: 'f50acaeec38c',
            _type: 'link',
            href: 'https://wordpress.com/',
          },
        ],
        style: 'normal',
      },
      {
        _key: '140f59838fac',
        _type: 'block',
        children: [
          {
            _key: '8e3ff5adb6900',
            _type: 'span',
            marks: [],
            text: 'My preferred software testing frameworks include ',
          },
          {
            _key: '8e3ff5adb6901',
            _type: 'span',
            marks: ['8bda755722f1'],
            text: 'Jest',
          },
          {
            _key: '8e3ff5adb6902',
            _type: 'span',
            marks: [],
            text: ' , ',
          },
          {
            _key: '8e3ff5adb6903',
            _type: 'span',
            marks: ['dbfe1bb0e8ca'],
            text: 'React Testing Library',
          },
          {
            _key: '8e3ff5adb6904',
            _type: 'span',
            marks: [],
            text: ', and ',
          },
          {
            _key: '8e3ff5adb6905',
            _type: 'span',
            marks: ['0eec85f9d1bf'],
            text: 'Playwright',
          },
          {
            _key: '8e3ff5adb6906',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [
          {
            _key: '8bda755722f1',
            _type: 'link',
            href: 'https://jestjs.io/',
          },
          {
            _key: 'dbfe1bb0e8ca',
            _type: 'link',
            href: 'https://testing-library.com/docs/react-testing-library/intro/',
          },
          {
            _key: '0eec85f9d1bf',
            _type: 'link',
            href: 'https://playwright.dev/',
          },
        ],
        style: 'normal',
      },
    ],
  },
}
